http:
 port: "8085"

request:
 host : "api.openweathermap.org"
 basepath : "/data/2.5"
 path : "/weather"
 
weatherapi:
 appid: "94a91ca29fe0e60a272f105e81f96777"
 
deployment:
 muleVersion: "4.3.0"
 username: "naishagupta1607"
 password: "Mulesoft@2021"
 applicationName: "weather-mule-app"
 environment: "Sandbox" 
 workers: "1"
 workerType: "MICRO"
 objectStoreV2: "true"
 deploymentTimeout: "2100000"
 env: "dev"
 client_id: "5a0b3cf0273642bfa56ca16fa5a99f36"
 client_secret: "0EfE786945dc41399D36ea4BFCa7a256"