http:
 port: "8085"

request:
 host : "api.openweathermap.org"
 basepath : "/data/2.5"
 path : "/weather"
 
weatherapi:
 appid: "94a91ca29fe0e60a272f105e81f96777"
 
deployment:
 muleVersion : "4.3.0"
 username : "naishagupta16072015"
 password : "Mulesoft@2021"
 applicationName: "weather-mule-app2"
 environment: "Sandbox" 
 workers: "1"
 workerType: "MICRO"
 objectStoreV2: "true"
 client_id: "930df5a4657e4f07a4fe1967d0485158"
 client_secret: "860f84d8A5fF4E058E46Be6A09C44f02"